default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password:
  pool: 5
  variables:
    tcp_keepalives_idle: 60
    tcp_keepalives_interval: 60
    tcp_keepalives_count: 100

development:
  <<: *default
  database: stat_development

test:
  <<: *default
  database: stat_test